#![allow(missing_docs)]
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ciphertext {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub c: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", tag = "2")]
    pub seed: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "3")]
    pub level: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RgswCiphertext {
    #[prost(message, optional, tag = "1")]
    pub ksk0: ::core::option::Option<KeySwitchingKey>,
    #[prost(message, optional, tag = "2")]
    pub ksk1: ::core::option::Option<KeySwitchingKey>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KeySwitchingKey {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub c0: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub c1: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", tag = "3")]
    pub seed: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "4")]
    pub ciphertext_level: u32,
    #[prost(uint32, tag = "5")]
    pub ksk_level: u32,
    #[prost(uint32, tag = "6")]
    pub log_base: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RelinearizationKey {
    #[prost(message, optional, tag = "1")]
    pub ksk: ::core::option::Option<KeySwitchingKey>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LbfvRelinearizationKey {
    #[prost(message, optional, tag = "1")]
    pub ksk_r_to_s: ::core::option::Option<KeySwitchingKey>,
    #[prost(message, optional, tag = "2")]
    pub ksk_s_to_r: ::core::option::Option<KeySwitchingKey>,
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub b_vec: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GaloisKey {
    #[prost(message, optional, tag = "1")]
    pub ksk: ::core::option::Option<KeySwitchingKey>,
    #[prost(uint32, tag = "2")]
    pub exponent: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvaluationKey {
    #[prost(message, repeated, tag = "2")]
    pub gk: ::prost::alloc::vec::Vec<GaloisKey>,
    #[prost(uint32, tag = "3")]
    pub ciphertext_level: u32,
    #[prost(uint32, tag = "4")]
    pub evaluation_key_level: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Parameters {
    #[prost(uint32, tag = "1")]
    pub degree: u32,
    #[prost(uint64, repeated, tag = "2")]
    pub moduli: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint32, tag = "4")]
    pub variance: u32,
    #[prost(oneof = "parameters::PlaintextModulus", tags = "3, 5")]
    pub plaintext_modulus: ::core::option::Option<parameters::PlaintextModulus>,
}
/// Nested message and enum types in `Parameters`.
pub mod parameters {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum PlaintextModulus {
        #[prost(uint64, tag = "3")]
        Plaintext(u64),
        #[prost(bytes, tag = "5")]
        PlaintextBig(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PublicKey {
    #[prost(message, optional, tag = "1")]
    pub c: ::core::option::Option<Ciphertext>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LbfvPublicKey {
    #[prost(message, repeated, tag = "1")]
    pub c: ::prost::alloc::vec::Vec<Ciphertext>,
    #[prost(uint32, tag = "2")]
    pub l: u32,
    #[prost(bytes = "vec", tag = "3")]
    pub seed: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PublicKeyShare {
    #[prost(message, optional, tag = "1")]
    pub p0: ::core::option::Option<Poly>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Poly {
    #[prost(message, optional, boxed, tag = "1")]
    pub p0: ::core::option::Option<::prost::alloc::boxed::Box<Poly>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SecretKey {
    #[prost(sint64, repeated, tag = "1")]
    pub coeffs: ::prost::alloc::vec::Vec<i64>,
}
