//! Encoder for the CKKS scheme: the canonical embedding.
//!
//! Maps vectors of up to `N/2` real values into ring elements of
//! `R_q = Z_q[X]/(X^N + 1)` and back. Encoding evaluates the inverse of the
//! canonical embedding `sigma: R -> C^{N/2}` (restricted to the conjugate
//! orbit generated by 5 modulo `2N`), scales by `delta`, and rounds to
//! integer coefficients.
//!
//! This implementation uses the direct `O(N^2)` transform. It is exact,
//! simple to review, and fast enough for the parameter sizes used in tests
//! and proof generation. An FFT-based encoder can replace it transparently
//! later.

use crate::ckks::{CkksParameters, CkksPlaintext};
use crate::{Error, Result};
use fhe_math::rq::{Poly, PowerBasis, traits::TryConvertFrom};
use num_bigint::{BigInt, BigUint};
use num_traits::ToPrimitive;
use std::f64::consts::PI;
use std::sync::Arc;

/// Encoder between real vectors and CKKS plaintexts.
#[derive(Debug, Clone)]
pub struct CkksEncoder {
    par: Arc<CkksParameters>,
    /// Exponents `5^j mod 2N` for `j` in `0..N/2`.
    root_exponents: Vec<usize>,
}

impl CkksEncoder {
    /// Create a new encoder for the given parameters.
    #[must_use]
    pub fn new(par: &Arc<CkksParameters>) -> Self {
        let n = par.degree();
        let m = 2 * n;
        let mut root_exponents = Vec::with_capacity(n / 2);
        let mut e = 1usize;
        for _ in 0..n / 2 {
            root_exponents.push(e);
            e = (e * 5) % m;
        }
        Self {
            par: par.clone(),
            root_exponents,
        }
    }

    /// Encode a slice of real values (at most `N/2`) into a plaintext at the
    /// given level, using the parameters' scale `delta`.
    ///
    /// The coefficient of `X^k` of the encoded polynomial is
    /// `round(delta * (2/N) * sum_j Re(z_j * conj(zeta_j)^k))`, where
    /// `zeta_j = exp(i*pi*e_j/N)` and `e_j = 5^j mod 2N`. This is the exact
    /// inverse of evaluating the polynomial at the `N` primitive `2N`-th
    /// roots of unity, restricted to conjugate-symmetric slot vectors.
    pub fn encode(&self, values: &[f64], level: usize) -> Result<CkksPlaintext> {
        self.encode_with_scale(values, level, self.par.scale())
    }

    /// Encode at an explicit scale instead of the parameter scale.
    ///
    /// Needed by leveled circuits: after a rescale a ciphertext's scale is
    /// `s^2 / q_dropped` (not the parameter scale), and plaintext operands
    /// that must add to or align with it need EXACTLY that scale.
    pub fn encode_with_scale(
        &self,
        values: &[f64],
        level: usize,
        scale: f64,
    ) -> Result<CkksPlaintext> {
        let n = self.par.degree();
        let slots = self.par.slots();
        if values.len() > slots {
            return Err(Error::InvalidPlaintext {
                reason: format!("too many values: {} exceeds {} slots", values.len(), slots),
            });
        }

        if !scale.is_finite() || scale <= 0.0 {
            return Err(Error::InvalidPlaintext {
                reason: format!("invalid encoding scale {scale}"),
            });
        }
        let delta = scale;
        let mut z = vec![0.0f64; slots];
        z[..values.len()].copy_from_slice(values);

        let mut coeffs = vec![0i64; n];
        let scale_factor = delta * 2.0 / (n as f64);
        for (k, coeff) in coeffs.iter_mut().enumerate() {
            let mut acc = 0.0f64;
            for (j, zj) in z.iter().enumerate() {
                // conj(zeta_j)^k = exp(-i*pi*e_j*k/N); Re(z_j * that) = z_j*cos.
                let angle = -PI * ((self.root_exponents[j] * k) as f64) / (n as f64);
                acc += zj * angle.cos();
            }
            let rounded = (scale_factor * acc).round();
            if !rounded.is_finite() || rounded.abs() >= (i64::MAX as f64) {
                return Err(Error::InvalidPlaintext {
                    reason: "encoded coefficient overflows i64".to_string(),
                });
            }
            *coeff = rounded as i64;
        }

        let ctx = self.par.context_at_level(level)?;
        let poly = Poly::<PowerBasis>::try_convert_from(coeffs.as_slice(), ctx, false)?.into_ntt();

        Ok(CkksPlaintext {
            par: self.par.clone(),
            poly,
            scale: delta,
            level,
        })
    }

    /// Decode a plaintext back into `N/2` real values.
    ///
    /// Evaluates the plaintext polynomial at the roots `zeta_j` and divides
    /// by the plaintext's scale.
    pub fn decode(&self, pt: &CkksPlaintext) -> Result<Vec<f64>> {
        let n = self.par.degree();
        let ctx = self.par.context_at_level(pt.level)?;
        let q = ctx.modulus();

        let coeffs_biguint = Vec::<BigUint>::from(&pt.poly.clone().into_power_basis());
        let half_q = q / 2u32;
        let coeffs: Vec<f64> = coeffs_biguint
            .iter()
            .map(|c| {
                let centered = if c > &half_q {
                    BigInt::from(c.clone()) - BigInt::from(q.clone())
                } else {
                    BigInt::from(c.clone())
                };
                centered.to_f64().unwrap_or(0.0)
            })
            .collect();

        let mut values = Vec::with_capacity(self.par.slots());
        for e_j in &self.root_exponents {
            let mut re = 0.0f64;
            for (k, ck) in coeffs.iter().enumerate().take(n) {
                let angle = PI * ((e_j * k) as f64) / (n as f64);
                re += ck * angle.cos();
            }
            values.push(re / pt.scale);
        }
        Ok(values)
    }
}

#[cfg(test)]
mod tests {
    use super::CkksEncoder;
    use crate::ckks::CkksParametersBuilder;
    use std::error::Error;

    #[test]
    fn encode_decode_roundtrip() -> Result<(), Box<dyn Error>> {
        let params = CkksParametersBuilder::new()
            .set_degree(32)
            .set_moduli_sizes(&[50, 40])
            .set_scale(2f64.powi(30))
            .build_arc()?;
        let encoder = CkksEncoder::new(&params);

        let values = vec![1.5, -2.25, 3.125, 0.0, 42.0, -0.5];
        let pt = encoder.encode(&values, 0)?;
        let decoded = encoder.decode(&pt)?;

        for (v, d) in values.iter().zip(decoded.iter()) {
            assert!(
                (v - d).abs() < 1e-6,
                "roundtrip error too large: {v} vs {d}"
            );
        }
        // Unused slots decode to ~0.
        for d in &decoded[values.len()..] {
            assert!(d.abs() < 1e-6);
        }
        Ok(())
    }

    #[test]
    fn too_many_values_rejected() -> Result<(), Box<dyn Error>> {
        let params = CkksParametersBuilder::new()
            .set_degree(16)
            .set_moduli_sizes(&[50])
            .set_scale(2f64.powi(30))
            .build_arc()?;
        let encoder = CkksEncoder::new(&params);
        assert!(encoder.encode(&[1.0; 9], 0).is_err());
        Ok(())
    }

    #[test]
    fn encode_at_lower_level() -> Result<(), Box<dyn Error>> {
        let params = CkksParametersBuilder::new()
            .set_degree(16)
            .set_moduli_sizes(&[50, 40])
            .set_scale(2f64.powi(30))
            .build_arc()?;
        let encoder = CkksEncoder::new(&params);
        let values = vec![std::f64::consts::PI];
        let pt = encoder.encode(&values, 1)?;
        let decoded = encoder.decode(&pt)?;
        assert!((decoded[0] - std::f64::consts::PI).abs() < 1e-6);
        Ok(())
    }
}
