#![allow(missing_docs)]
// This file is @generated by prost-build.
/// MBFV share envelopes (experimental crate).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PublicKeyShare {
    #[prost(message, optional, tag = "1")]
    pub p0: ::core::option::Option<Poly>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Poly {
    #[prost(message, optional, boxed, tag = "1")]
    pub p0: ::core::option::Option<::prost::alloc::boxed::Box<Poly>>,
}
