#![allow(missing_docs)]
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LbfvPublicKey {
    #[prost(message, repeated, tag = "1")]
    pub c: ::prost::alloc::vec::Vec<crate::proto::bfv::Ciphertext>,
    #[prost(uint32, tag = "2")]
    pub l: u32,
    #[prost(bytes = "vec", tag = "3")]
    pub seed: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LbfvRelinearizationKey {
    #[prost(message, optional, tag = "1")]
    pub ksk_r_to_s: ::core::option::Option<crate::proto::bfv::KeySwitchingKey>,
    #[prost(message, optional, tag = "2")]
    pub ksk_s_to_r: ::core::option::Option<crate::proto::bfv::KeySwitchingKey>,
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub b_vec: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
