//! Smudging-bound configuration and arithmetic.

use crate::Error;
use crate::bfv::BfvParameters;
use fhe_math::rq::error_coefficient_bound;
use num_bigint::BigUint;
use num_traits::Zero;
use std::sync::Arc;

/// Maximum statistical security parameter accepted for the smudging bound.
///
/// The smudging bound is `B_sm = 2^(lambda + 1) * d * B_C` (`d` = polynomial
/// degree); larger values are computationally infeasible to represent, so
/// values above this ceiling are rejected to prevent massive allocations
/// from huge BigUint shifts. How much statistical hiding a given lambda
/// provides depends on the full parameter set (degree, moduli, plaintext
/// modulus, circuit depth), so this is the only lambda bound the library
/// enforces: callers choose lambda according to their deployment's policy.
pub const MAX_LAMBDA: usize = 256;

/// Model of the encryption path that produced the fresh ciphertexts whose
/// decryption noise the smudging noise must hide.
///
/// The decryption noise of a fresh ciphertext encrypted under an aggregated
/// threshold key is bounded by
///
/// > `B_fresh = d · u_bound · e_pk + B_enc + d · e2_bound · sk_bound`
///
/// where `d` is the ring degree, `B_enc` is the worst-case coefficient bound
/// of the first encryption error (`e1`) term,
/// [`fhe_math::rq::error_coefficient_bound`] of `error1_variance`, `e2_bound`
/// is `2 · variance` for the second encryption error (`e2`) term, `sk_bound`
/// is `n` for the aggregated ternary secret key, and `e_pk` is
/// `n · (2 · variance)` for the aggregated public-key error (each share
/// contributes an error bounded by `2 · variance`, so a single-party key is
/// bounded by `2 · variance`). The selected model supplies `u_bound`, the
/// actual coefficient support of the encryption randomness `u`:
///
/// - [`FreshNoiseModel::BfvPublicKey`]: `u_bound = 1`. `bfv::PublicKey`
///   samples `u` from the ternary CBD used for secret keys
///   (`sample_vec_cbd_f32` with variance `0.5`).
/// - [`FreshNoiseModel::LbfvPublicKey`]: `u_bound = 2 · variance`.
///   `lbfv::LBFVPublicKey` samples `u` with `Poly::small(params.variance)`,
///   whose support is wider than ternary.
/// - [`FreshNoiseModel::BfvSecretKey`]: secret-key encryption samples no `u`;
///   the phase of a fresh ciphertext is exactly `e + m` with `‖e‖∞ ≤
///   2 · variance`, so `B_fresh = 2 · variance`.
/// - [`FreshNoiseModel::Custom`]: a caller-justified `B_fresh` for inputs the
///   library cannot model; see the variant's documentation for the trust
///   requirements.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FreshNoiseModel {
    /// Ciphertexts produced by `bfv::PublicKey::try_encrypt`, including keys
    /// aggregated from MBFV public-key shares (`mbfv::PublicKeyShare`).
    ///
    /// The encryption randomness is ternary (`‖u‖∞ ≤ 1`).
    BfvPublicKey,
    /// Ciphertexts produced by `lbfv::LBFVPublicKey::try_encrypt`, including
    /// keys aggregated from distributed l-BFV public-key shares.
    ///
    /// The encryption randomness is sampled with `Poly::small(variance)`
    /// (`‖u‖∞ ≤ 2 · variance`), so the fresh-noise bound is larger than for
    /// [`FreshNoiseModel::BfvPublicKey`] at otherwise identical parameters.
    LbfvPublicKey,
    /// Ciphertexts produced by `bfv::SecretKey::try_encrypt`.
    ///
    /// Secret-key encryption uses no randomness polynomial `u` and no
    /// public-key error: the fresh phase noise is a single small error with
    /// `‖e‖∞ ≤ 2 · variance`, so `B_fresh = 2 · variance`.
    BfvSecretKey,
    /// A caller-supplied `B_fresh` for ciphertexts whose provenance the
    /// library cannot verify: imported ciphertexts, keys generated by other
    /// implementations, or nonstandard samplers.
    ///
    /// # Trust and provenance
    ///
    /// The bound is trusted, not checked. This library cannot verify the
    /// noise distribution of an externally supplied key or ciphertext; the
    /// caller must justify the bound from the actual key-generation and
    /// encryption procedure, and a bound that understates the real noise
    /// invalidates the smudging guarantee. When the ciphertexts fed to one
    /// decryption are heterogeneous (produced under different keys or
    /// samplers), supply the maximum of the individual bounds. The value must
    /// be positive; a zero bound is rejected.
    Custom(BigUint),
}

/// Configuration for calculating and generating threshold BFV smudging noise.
///
/// The bound is derived from these caller-selected inputs when a
/// [`crate::trbfv::smudging::SmudgingNoiseGenerator`] is created.
/// Configuration inputs validated by [`Self::new`] cannot be changed directly.
///
/// # Caller responsibilities
///
/// The circuit size `m` (see below), the multiplicative depth, `lambda`, and
/// the [`FreshNoiseModel`] are caller choices. Together they determine the
/// bound: `m` and the depth drive the ciphertext-noise bound `B_C` and whether
/// the strict correctness inequality is feasible at all, `lambda` scales the
/// resulting smudging bound `B_sm`, and the model supplies the
/// fresh-ciphertext noise bound `B_fresh` (issue #250). Callers must select
/// the model that matches the encryption path that actually produced the
/// input ciphertexts; the library applies no silent default. A dealing
/// manager ([`crate::trbfv::ShareManager::generate_smudging_shares`]) verifies
/// a noise owner's party count and complete BFV parameter set, but
/// deliberately does not verify `m`, depth, `lambda`, or the model; callers
/// must configure them for the circuits and ciphertexts they evaluate. The
/// circuit-size guidance in the next section is scoped to the bound formula
/// this API implements; it is not a general analysis of arbitrary circuits.
///
/// # Choosing the circuit size `m`
///
/// `m` is an upper bound on the number of *fresh* ciphertexts that are summed
/// together **before** the modelled circuit consumes them. It is not the
/// number of output ciphertexts, and it is not the number of independent
/// decryptions: one smudging deal covers one evaluated ciphertext.
///
/// - Additive circuit `ct_a + ct_b + ct_c`: three fresh ciphertexts are
///   summed before decryption, so `m = 3`.
/// - Pure multiplication of fresh inputs with no pre-sum, e.g.
///   `ct_a * ct_b * ct_c`: each multiplication branch carries the noise of
///   one fresh ciphertext, so `m = 1` even though several input ciphertexts
///   feed the product.
/// - Mixed circuit `(ct_a + ct_b) * ct_c`: the left branch is a two-input
///   sum, so the worst pre-multiplication fan-in is `m = 2`.
///
/// In general, set `m` to the worst fan-in of additions over fresh
/// ciphertexts performed *before* any multiplication. If the circuit also
/// adds evaluated results *after* a multiplication, this bound formula does
/// not model that growth: analyze the circuit and supply a conservative
/// circuit-specific `m` (or otherwise refresh the ciphertext); this API makes
/// no generic circuit-size guarantee. A larger `m` only inflates `B_C` and
/// `B_sm`, so overprovisioning stays correct and safe at a feasibility cost.
///
/// ```
/// use fhe::bfv::BfvParametersBuilder;
/// use fhe::trbfv::{FreshNoiseModel, SmudgingConfig};
/// use std::sync::Arc;
///
/// // Small fast parameters; only the circuit-size choice is exercised here.
/// let params = BfvParametersBuilder::new()
///     .set_degree(8)
///     .set_plaintext_modulus(2)
///     .set_moduli(&[65537])
///     .build_arc()
///     .unwrap();
///
/// // No pre-sum: a single fresh ciphertext, or a pure product of fresh
/// // ciphertexts such as `a * b * c`, sums no fresh ciphertexts before the
/// // circuit, so the worst pre-multiplication fan-in is `m = 1`.
/// let no_pre_sum = SmudgingConfig::new(
///     Arc::clone(&params),
///     3, // parties
///     1, // m: no fresh ciphertexts are summed before the circuit
///     2, // lambda (caller-selected policy)
///     FreshNoiseModel::BfvPublicKey,
/// )
/// .unwrap();
/// assert_eq!(no_pre_sum.m(), 1);
///
/// // `(a + b) * c`: the left branch sums two fresh ciphertexts before the
/// // multiplication, so `m = 2` even though three ciphertexts feed the
/// // circuit and it has one output.
/// let mixed = SmudgingConfig::new(
///     params,
///     3,
///     2, // m: worst pre-multiplication fan-in of `(a + b) * c`
///     2,
///     FreshNoiseModel::BfvPublicKey,
/// )
/// .unwrap();
/// assert_eq!(mixed.m(), 2);
/// assert_eq!(mixed.n(), 3);
/// assert_eq!(mixed.lambda(), 2);
/// ```
///
/// ```compile_fail
/// # use fhe::trbfv::smudging::SmudgingConfig;
/// fn change_party_count(config: &mut SmudgingConfig) {
///     config.n = 0;
/// }
/// ```
#[non_exhaustive]
#[derive(Debug, Clone)]
pub struct SmudgingConfig {
    /// BFV parameters (degree, moduli, plaintext modulus)
    pub(super) params: Arc<BfvParameters>,
    /// Number of parties in the threshold scheme
    pub(super) n: usize,
    /// Upper bound on the number of fresh ciphertexts summed before the
    /// modelled circuit (worst pre-multiplication fan-in); see
    /// [`Self::new`] and the type-level "Choosing the circuit size `m`"
    /// section. Not the count of output ciphertexts or decryptions.
    pub(super) m: usize,
    /// Statistical security parameter: the smudging bound grows as
    /// `2^(lambda + 1) * d * B_C`. Larger values give stronger statistical
    /// hiding; values above [`MAX_LAMBDA`] are rejected. Choosing lambda for
    /// a deployment is the caller's policy.
    pub(super) lambda: usize,
    /// Multiplicative circuit depth (0 for additive-only circuits).
    ///
    /// When non-zero, [`crate::trbfv::smudging::SmudgingNoiseGenerator::new`]
    /// applies the Prop. 20 noise growth recursion for each level before
    /// computing `B_sm`.
    pub(super) mult_depth: u32,
    /// Encryption-path model supplying the fresh-ciphertext noise bound
    /// `B_fresh` (issue #250). Selected explicitly by the caller in
    /// [`Self::new`]; there is no silent default.
    pub(super) model: FreshNoiseModel,
}

/// Compute a coefficient bound (B_enc) from the configured error sampler variance.
///
/// Uses the same worst-case coefficient bound as the encryption sampler.
pub(super) fn compute_b_enc(error1_variance: &BigUint) -> crate::Result<BigUint> {
    Ok(error_coefficient_bound(error1_variance)?)
}

/// Compute Q = product of all moduli as a BigUint.
pub(super) fn modulus_product(moduli: &[u64]) -> BigUint {
    let mut q = BigUint::from(1_u64);
    for &qi in moduli {
        q *= BigUint::from(qi);
    }
    q
}

/// Compute Delta = floor(Q / t), the exact plaintext scaling factor.
pub(super) fn compute_delta(q: &BigUint, t: &BigUint) -> BigUint {
    q / t
}

impl SmudgingConfig {
    /// Return the BFV parameters for this configuration.
    #[must_use]
    pub fn params(&self) -> &Arc<BfvParameters> {
        &self.params
    }

    /// Return the party count.
    #[must_use]
    pub fn n(&self) -> usize {
        self.n
    }

    /// Return the maximum number of fresh ciphertexts summed before the
    /// modelled circuit (`m`).
    ///
    /// This is the circuit-size input the caller chose: the worst fan-in of
    /// pre-circuit additions over fresh ciphertexts. It is not the number of
    /// output ciphertexts or independent decryptions; see
    /// [`SmudgingConfig`] for how to choose it.
    #[must_use]
    pub fn m(&self) -> usize {
        self.m
    }

    /// Return the statistical security parameter.
    #[must_use]
    pub fn lambda(&self) -> usize {
        self.lambda
    }

    /// Return the multiplicative depth (zero for additive-only circuits).
    #[must_use]
    pub fn mult_depth(&self) -> u32 {
        self.mult_depth
    }

    /// Set the circuit depth before creating a smudging noise generator.
    ///
    /// The resulting bound is checked for feasibility by
    /// [`crate::trbfv::smudging::SmudgingNoiseGenerator::new`], including
    /// during the depth recursion.
    #[must_use]
    pub fn with_mult_depth(mut self, depth: u32) -> Self {
        self.mult_depth = depth;
        self
    }

    /// Return the selected fresh-noise model.
    #[must_use]
    pub fn model(&self) -> &FreshNoiseModel {
        &self.model
    }

    /// Worst-case bound `B_fresh` on the decryption noise of a fresh
    /// ciphertext produced by this configuration's modelled encryption path.
    ///
    /// See [`FreshNoiseModel`] for the per-path derivation and the actual
    /// sampler supports this bound relies on.
    pub(super) fn fresh_noise_bound(&self) -> crate::Result<BigUint> {
        if let FreshNoiseModel::Custom(bound) = &self.model
            && bound.is_zero()
        {
            // Defense in depth against a configuration whose private fields
            // were corrupted after `new` validated them.
            return Err(Error::smudging_bound_infeasible(
                "custom fresh-noise bound must be positive",
            ));
        }
        let variance = self.params.variance();
        let b_e = BigUint::from((2 * variance) as u64);
        let d = BigUint::from(self.params.degree());
        let b_enc = compute_b_enc(self.params.get_error1_variance())?;
        // BigUint products throughout: a large party count must overflow into
        // an infeasible bound, never wrap into an understated one.
        let e_pk = BigUint::from(self.n) * &b_e;
        let sk_bound = BigUint::from(self.n);
        Ok(match &self.model {
            FreshNoiseModel::BfvPublicKey => &d * &e_pk + b_enc + &d * &b_e * &sk_bound,
            FreshNoiseModel::LbfvPublicKey => {
                // l-BFV samples `u` with `Poly::small(variance)`, whose
                // coefficient support reaches `2 * variance` (issue #250).
                let u_bound = BigUint::from((2 * variance) as u64);
                &d * &u_bound * &e_pk + b_enc + &d * &b_e * &sk_bound
            }
            // Secret-key encryption samples no randomness `u`: the phase of a
            // fresh ciphertext is exactly `e + m`, so `B_fresh = 2 * variance`.
            FreshNoiseModel::BfvSecretKey => b_e,
            FreshNoiseModel::Custom(bound) => bound.clone(),
        })
    }

    /// Create a new smudging configuration with an explicit fresh-noise model.
    ///
    /// # Arguments
    /// * `params` - BFV parameters
    /// * `n` - Number of parties in threshold scheme
    /// * `m` - Upper bound on the number of *fresh* ciphertexts summed
    ///   together before the modelled circuit, i.e. the worst fan-in of
    ///   pre-circuit additions over fresh ciphertexts. This is not the count
    ///   of output ciphertexts or independent decryptions: a pure
    ///   multiplication of fresh inputs with no pre-sum uses `m = 1` per
    ///   branch, while `(ct_a + ct_b) * ct_c` uses `m = 2` because the left
    ///   branch sums two fresh ciphertexts. Additions of evaluated results
    ///   after a multiplication are not modelled by the formula; choose a
    ///   conservative circuit-specific `m` after analyzing such a circuit.
    ///   See the type-level "Choosing the circuit size `m`" section.
    /// * `lambda` - Statistical security level
    /// * `model` - Model of the encryption path that produced the input
    ///   ciphertexts. Select [`FreshNoiseModel::BfvPublicKey`],
    ///   [`FreshNoiseModel::LbfvPublicKey`], or
    ///   [`FreshNoiseModel::BfvSecretKey`] to match the actual library path,
    ///   or [`FreshNoiseModel::Custom`] with a caller-justified bound for
    ///   imported ciphertexts. There is deliberately no default: the ternary
    ///   randomness assumption is only valid for the BFV public-key path.
    ///   When input ciphertexts come from several of these paths, use the
    ///   model with the largest `B_fresh` (for `Custom`, the maximum bound).
    ///
    /// # Errors
    /// Returns an error when `n` or `m` is zero, when `lambda` exceeds
    /// [`MAX_LAMBDA`], or when a [`FreshNoiseModel::Custom`] bound is zero.
    pub fn new(
        params: Arc<BfvParameters>,
        n: usize,
        m: usize,
        lambda: usize,
        model: FreshNoiseModel,
    ) -> Result<Self, Error> {
        if n == 0 {
            return Err(Error::smudging_bound_infeasible(
                "number of parties n must be positive",
            ));
        }
        if m == 0 {
            return Err(Error::smudging_bound_infeasible(
                "number of ciphertexts m must be positive",
            ));
        }
        if lambda > MAX_LAMBDA {
            return Err(Error::smudging_bound_infeasible(format!(
                "lambda {lambda} exceeds maximum feasible value {MAX_LAMBDA}"
            )));
        }
        if let FreshNoiseModel::Custom(bound) = &model
            && bound.is_zero()
        {
            return Err(Error::smudging_bound_infeasible(
                "custom fresh-noise bound must be positive",
            ));
        }
        Ok(Self {
            params,
            n,
            m,
            lambda,
            mult_depth: 0,
            model,
        })
    }
}
