# https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
name: Rust
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
<<<<<<< HEAD
=======
    paths-ignore:
      - 'README.md'

name: Test
>>>>>>> upstream/main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v4

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.85.0

      - name: Install protobuf compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Check code format
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --all-features
=======
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/checkout@v6
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    env:
      CARGO_INCREMENTAL: 0
      CARGO_TERM_COLOR: always
    runs-on: ubuntu-latest
    steps:
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/checkout@v6
      - uses: actions-rs/cargo@v1
        with:
          command: test
>>>>>>> upstream/main
